const PREMIOS = [
    { numero: 1, premio: "PLACA VITROCERAMICA 1H con olla -TOKYO" },
    { numero: 2, premio: "PLACA VITROCERAMICA 1H con olla -TOKYO" },
    { numero: 3, premio: "PLACA VITROCERAMICA 1H con olla -TOKYO" },
    { numero: 4, premio: "PLACA VITROCERAMICA 1H con olla -TOKYO" },
    { numero: 5, premio: "PLACA VITROCERAMICA 1H con olla -TOKYO" },
    { numero: 6, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 7, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 8, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 9, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 10, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 11, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 12, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 13, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX -TOKYO" },
    { numero: 14, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 15, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 16, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 17, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 18, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 19, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 20, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 21, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 22, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 23, premio: "SANDWICHERA 2P TOKYO" },
    { numero: 24, premio: "CAFETERA CAFÉ TIME - ARNO" },
    { numero: 25, premio: "CAFETERA CAFÉ TIME - ARNO" },
    { numero: 26, premio: "CAFETERA CAFÉ TIME - ARNO" },
    { numero: 27, premio: "CAFETERA CAFÉ TIME - ARNO" },
    { numero: 28, premio: "CAFETERA CAFÉ TIME - ARNO" },
    { numero: 29, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 30, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 31, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 32, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 33, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 34, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 35, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 36, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 37, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 38, premio: "LICUADORA 5 VELOC - TOKYO" },
    { numero: 39, premio: "VENTILADOR DE PIE TURBO - TOKYO" },
    { numero: 40, premio: "VENTILADOR DE PIE TURBO - TOKYO" },
    { numero: 41, premio: "VENTILADOR DE PIE TURBO - TOKYO" },
    { numero: 42, premio: "VENTILADOR DE PIE TURBO - TOKYO" },
    { numero: 43, premio: "VENTILADOR DE PIE TURBO - TOKYO" },
    { numero: 44, premio: "HIDROLAVADORA 1900W C/A Michelin" },
    { numero: 45, premio: "HIDROLAVADORA 1900W C/A Michelin" },
    { numero: 46, premio: "HIDROLAVADORA 1900W C/A Michelin" },
    { numero: 47, premio: "RADIO PORTATIL BOM BOX NARANJA -TOKYO" },
    { numero: 48, premio: "RADIO PORTATIL BOM BOX NARANJA -TOKYO" },
    { numero: 49, premio: "RADIO PORTATIL BOM BOX NARANJA -TOKYO" },
    { numero: 50, premio: "RADIO PORTATIL BOM BOX NARANJA -TOKYO" },
    { numero: 51, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 52, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 53, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 54, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 55, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 56, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 57, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 58, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 59, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 60, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 61, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 62, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 63, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 64, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 65, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 66, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 67, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 68, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 69, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 70, premio: "VENTILADOR DE TECHO - WAHSON" },
    { numero: 71, premio: "BAFLE PORTATIL 12 TOKYO" },
    { numero: 72, premio: "BAFLE PORTATIL 12 TOKYO" },
    { numero: 73, premio: "BAFLE PORTATIL 12 TOKYO" },
    { numero: 74, premio: "BAFLE PORTATIL 12 TOKYO" },
    { numero: 75, premio: "BAFLE PORTATIL 12 TOKYO" },
    { numero: 76, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 77, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 78, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 79, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 80, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 81, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 82, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 83, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 84, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 85, premio: "PISCINA 5000 LTS - BEST WAY" },
    { numero: 86, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 87, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 88, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 89, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 90, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 91, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 92, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 93, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 94, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 95, premio: "MICROONDAS 20 LTS - TOKYO" },
    { numero: 96, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 97, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 98, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 99, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 100, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 101, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 102, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 103, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 104, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 105, premio: "COCINA 4H M/INOX - ATLAS" },
    { numero: 106, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 107, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 108, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 109, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 110, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 111, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 112, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 113, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 114, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 115, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 116, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 117, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 118, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 119, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 120, premio: "HORNO ELECTRICO DE 45 LTS - JAM" },
    { numero: 121, premio: "LAVARROPAS 5 K - TOKYO" },
    { numero: 122, premio: "LAVARROPAS 5 K - TOKYO" },
    { numero: 123, premio: "LAVARROPAS 5 K - TOKYO" },
    { numero: 124, premio: "HELADERA MAGNA 300 2P - TOKYO" },
    { numero: 125, premio: "HELADERA MAGNA 300 2P - TOKYO" },
    { numero: 126, premio: "HELADERA MAGNA 300 2P - TOKYO" },
    { numero: 127, premio: "HELADERA MAGNA 300 2P - TOKYO" },
    { numero: 128, premio: "HELADERA MAGNA 300 2P - TOKYO" },
    { numero: 129, premio: "FREEZER VERTICAL 5 CAJONES - JAM" },
    { numero: 130, premio: "FREEZER VERTICAL 5 CAJONES - JAM" },
    { numero: 131, premio: "FREEZER VERTICAL 5 CAJONES - JAM" },
    { numero: 132, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 133, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 134, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 135, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 136, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 137, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 138, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 139, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 140, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 141, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 142, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 143, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 144, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 145, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 146, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 147, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 148, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 149, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 150, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 151, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 152, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 153, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 154, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 155, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 156, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU - TOKYO" },
    { numero: 157, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL - MABE" },
    { numero: 158, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL - MABE" },
    { numero: 159, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL - MABE" },
    { numero: 160, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL - MABE" },
    { numero: 161, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL - MABE" },
    { numero: 162, premio: "TV LED 43 SMART - JVC" },
    { numero: 163, premio: "TV LED 43 SMART - JVC" },
    { numero: 164, premio: "TV LED 43 SMART - JVC" },
    { numero: 165, premio: "TV LED 43 SMART - JVC" },
    { numero: 166, premio: "TV LED 43 SMART - JVC" },
    { numero: 167, premio: "NOTEBOOK 14" },
    { numero: 168, premio: "NOTEBOOK 14" },
    { numero: 169, premio: "TV LED 50 SMART - AIWA" },
    { numero: 170, premio: "TV LED 50 SMART - AIWA" },
    { numero: 171, premio: "TV LED 50 SMART - AIWA" },
    { numero: 172, premio: "TV LED 50 SMART - AIWA" },
    { numero: 173, premio: "TV LED 50 SMART - AIWA" },
    { numero: 174, premio: "TV LED 50 SMART - AIWA" },
    { numero: 175, premio: "TV LED 50 SMART - AIWA" },
    { numero: 176, premio: "TV LED 50 SMART - AIWA" },
    { numero: 177, premio: "HELADERA 2P F/S 400 LTS INOX WHIRLPOOL" },
    { numero: 178, premio: "HELADERA 2P F/S 400 LTS INOX WHIRLPOOL" },
    { numero: 179, premio: "HELADERA 2P F/S 400 LTS INOX WHIRLPOOL" }
];