const PREMIOS = [
  { numero: 1, premio: "SANDWICHERA 2P JAM" },
  { numero: 2, premio: "SANDWICHERA 2P JAM" },
  { numero: 3, premio: "SANDWICHERA 2P JAM" },
  { numero: 4, premio: "SANDWICHERA 2P JAM" },
  { numero: 5, premio: "SANDWICHERA 2P JAM" },
  { numero: 6, premio: "SANDWICHERA 2P JAM" },
  { numero: 7, premio: "SANDWICHERA 2P JAM" },
  { numero: 8, premio: "SANDWICHERA 2P JAM" },
  { numero: 9, premio: "SANDWICHERA 2P JAM" },
  { numero: 10, premio: "SANDWICHERA 2P JAM" },

  { numero: 11, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 12, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 13, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 14, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 15, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 16, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 17, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },
  { numero: 18, premio: "HERVIDORA GLASS 1.7 LTS. JARRA INOX TOKYO" },

  { numero: 19, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 20, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 21, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 22, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 23, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 24, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 25, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 26, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 27, premio: "LICUADORA 5 VELOC ARNO" },
  { numero: 28, premio: "LICUADORA 5 VELOC ARNO" },

  { numero: 29, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 30, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 31, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 32, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 33, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 34, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 35, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 36, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 37, premio: "VENTILADOR DE PIE TURBO TOKYO" },
  { numero: 38, premio: "VENTILADOR DE PIE TURBO TOKYO" },

  { numero: 39, premio: "AIR FRYER 5.7 LTS B+D" },
  { numero: 40, premio: "AIR FRYER 5.7 LTS B+D" },
  { numero: 41, premio: "AIR FRYER 5.7 LTS B+D" },

  { numero: 42, premio: "PLACA COMBINADA 2H TOKYO" },
  { numero: 43, premio: "PLACA COMBINADA 2H TOKYO" },
  { numero: 44, premio: "PLACA COMBINADA 2H TOKYO" },
  { numero: 45, premio: "PLACA COMBINADA 2H TOKYO" },
  { numero: 46, premio: "PLACA COMBINADA 2H TOKYO" },

  // 47–66 VENTILADOR DE TECHO WATSON (20)
  { numero: 47, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 48, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 49, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 50, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 51, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 52, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 53, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 54, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 55, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 56, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 57, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 58, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 59, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 60, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 61, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 62, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 63, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 64, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 65, premio: "VENTILADOR DE TECHO WATSON" },
  { numero: 66, premio: "VENTILADOR DE TECHO WATSON" },

  // 67–76 MICROONDAS (10)
  { numero: 67, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 68, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 69, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 70, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 71, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 72, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 73, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 74, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 75, premio: "MICROONDAS 20 LTS TOKYO" },
  { numero: 76, premio: "MICROONDAS 20 LTS TOKYO" },

  // 77–81 COCINA (5)
  { numero: 77, premio: "COCINA 4H M/INOX ATLAS" },
  { numero: 78, premio: "COCINA 4H M/INOX ATLAS" },
  { numero: 79, premio: "COCINA 4H M/INOX ATLAS" },
  { numero: 80, premio: "COCINA 4H M/INOX ATLAS" },
  { numero: 81, premio: "COCINA 4H M/INOX ATLAS" },

  // 82–84 LAVARROPAS (3)
  { numero: 82, premio: "LAVARROPAS 7K TOKYO" },
  { numero: 83, premio: "LAVARROPAS 7K TOKYO" },
  { numero: 84, premio: "LAVARROPAS 7K TOKYO" },

  // 85–99 HORNO (15)
  { numero: 85, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 86, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 87, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 88, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 89, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 90, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 91, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 92, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 93, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 94, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 95, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 96, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 97, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 98, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },
  { numero: 99, premio: "HORNO ELECTRICO DE 45 LTS TOKYO" },

  // 100–104 BEBEDERO (5)
  { numero: 100, premio: "BEBEDERO DE MESA F/C TOKYO" },
  { numero: 101, premio: "BEBEDERO DE MESA F/C TOKYO" },
  { numero: 102, premio: "BEBEDERO DE MESA F/C TOKYO" },
  { numero: 103, premio: "BEBEDERO DE MESA F/C TOKYO" },
  { numero: 104, premio: "BEBEDERO DE MESA F/C TOKYO" },

  // 105–109 BAFLE (5)
  { numero: 105, premio: 'BAFLE PORTATIL 12" TOKYO' },
  { numero: 106, premio: 'BAFLE PORTATIL 12" TOKYO' },
  { numero: 107, premio: 'BAFLE PORTATIL 12" TOKYO' },
  { numero: 108, premio: 'BAFLE PORTATIL 12" TOKYO' },
  { numero: 109, premio: 'BAFLE PORTATIL 12" TOKYO' },

  // 110–119 HUMIDIFICADOR (10)
  { numero: 110, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 111, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 112, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 113, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 114, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 115, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 116, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 117, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 118, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },
  { numero: 119, premio: "VENTILADOR CON HUMIDIFICADOR TOKYO" },

  // 120–122 HIDROLAVADORA (3)
  { numero: 120, premio: "HIDROLAVADORA 1900W C/A TOKYO" },
  { numero: 121, premio: "HIDROLAVADORA 1900W C/A TOKYO" },
  { numero: 122, premio: "HIDROLAVADORA 1900W C/A TOKYO" },

  // 123–124 PARLANTE (2)
  { numero: 123, premio: "PARLANTE C/P MICROF KOLKE" },
  { numero: 124, premio: "PARLANTE C/P MICROF KOLKE" },

  // 125–129 FABRICADORA (5)
  { numero: 125, premio: "FABRICADORA DE HIELO FAMILIAR INOX TOKYO" },
  { numero: 126, premio: "FABRICADORA DE HIELO FAMILIAR INOX TOKYO" },
  { numero: 127, premio: "FABRICADORA DE HIELO FAMILIAR INOX TOKYO" },
  { numero: 128, premio: "FABRICADORA DE HIELO FAMILIAR INOX TOKYO" },
  { numero: 129, premio: "FABRICADORA DE HIELO FAMILIAR INOX TOKYO" },

  // 130–139 HELADERA MAGNA 300 (10)
  { numero: 130, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 131, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 132, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 133, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 134, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 135, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 136, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 137, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 138, premio: "HELADERA MAGNA 300 2P TOKYO" },
  { numero: 139, premio: "HELADERA MAGNA 300 2P TOKYO" },

  // 140–144 TV 43 (5)
  { numero: 140, premio: 'TV LED 43" SMART TOKYO' },
  { numero: 141, premio: 'TV LED 43" SMART TOKYO' },
  { numero: 142, premio: 'TV LED 43" SMART TOKYO' },
  { numero: 143, premio: 'TV LED 43" SMART TOKYO' },
  { numero: 144, premio: 'TV LED 43" SMART TOKYO' },

  // 145–152 TV 50 (8)
  { numero: 145, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 146, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 147, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 148, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 149, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 150, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 151, premio: 'TV LED 50" SMART TOKYO' },
  { numero: 152, premio: 'TV LED 50" SMART TOKYO' },

  // 153–154 NOTEBOOK (2)
  { numero: 153, premio: "NOTEBOOK 14 HP" },
  { numero: 154, premio: "NOTEBOOK 14 HP" },

  // 155–182 AIRE (28)
  { numero: 155, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 156, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 157, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 158, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 159, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 160, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 161, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 162, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 163, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 164, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 165, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 166, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 167, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 168, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 169, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 170, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 171, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 172, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 173, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 174, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 175, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 176, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 177, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 178, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 179, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 180, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 181, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },
  { numero: 182, premio: "AIRE ACONDICIONADO SPLIT 12.000 BTU TOKYO" },

  // 183–187 MAGNA PLUS (5)
  { numero: 183, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL TOKYO" },
  { numero: 184, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL TOKYO" },
  { numero: 185, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL TOKYO" },
  { numero: 186, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL TOKYO" },
  { numero: 187, premio: "HELADERA 2P F/H MAGNA PLUS 350 BL TOKYO" },

  // 188–190 WHIRLPOOL (3)
  { numero: 188, premio: "HELADERA 2P F/S 400 LTS INOX WHIRLPOOL" },
  { numero: 189, premio: "HELADERA 2P F/S 400 LTS INOX WHIRLPOOL" },
  { numero: 190, premio: "HELADERA 2P F/S 400 LTS INOX WHIRLPOOL" }
];
